---
title: "Reverse Survival x5"
author: "Jose H C Monteiro da Silva, Helena C Castanheira"
date: "2021-06-03"
output: pdf_document
bibliography: bibliography.bib
---

# Reverse Survival x5 version

In this short note we present the differences between the original version and the x5 version of the Reverse Survival method implemented in the package *fertestr*. 

The original version (let's call it x1) reconstructs the TFRs and birth counts (we call it $B^t$) for 15 points in time preceeding the date of inquiry each one corresponding to each single age of children's population count input (for ages 0 to 14). In the x5 version, we reconstruct the TFRs and $B^t$ for each five year period before the inquiry based on population counts of children reported in five-year age groups (0-4, 5-9, 10-14). Therefore, the main difference of these two approaches lies in the reconstruction of $B^t$ through reverse survival. 

In the x1 approach, the inputs for computing $B^t$ are: 1) population of children from 0-14 in single age groups, 2) a 'standard' survival function in single ages from ages 0 to 15 ($lx$), 3) estimates of child mortality probability for each three five year period preceding the inquiry ($_5q_0^{t-2.5}$, $_5q_0^{t-7.5}$, $_5q_0^{t-12.5}$). The original version of the x1 approach [@moultrie_etal2013] uses the logit transformation of the standard survival function and the mortality probabilities of prior periods to retrieve survival functions and from them compute the "proportion of births occurring $x$ to $x+1$ years earlier that survive to the time of the inquiry, $^cL_x$". Details of this approach can be viewed in the spreadsheet attached to the method's explanation in [http://demographicestimation.iussp.org/content/estimation-fertility-reverse-survival](http://demographicestimation.iussp.org/content/estimation-fertility-reverse-survival).

For the x5 alternative version, the inputs for computing $B^t$ are similar: 1) population counts of children reported in five-year age groups, 2) a 'standard' survival function for ages 5, 10 and 15 ($l_5,l_{10},l_{15}$ - $lx$ radix $l_0$ set to 1), 3) estimates of child mortality probability for each three five year period preceding the inquiry ($_5q_0^{t-2.5}$, $_5q_0^{t-7.5}$, $_5q_0^{t-12.5}$). The estimation procedure of $^cL_x$ (proportion of births occurring $x$ to $x+5$ years earlier that survive to the time of the inquiry) for periods $x = 2.5$ (0-4 years earlier), $x = 7.5$ (5-9 years earlier) and $x = 12.5$ (10-14 years earlier) follow the same strategy of the the original x1 version of the method, and will be described bellow.

## Step 1: From $_5q_0$, compute $\alpha^t$

We compute the intercept $\alpha^t$ of the linear relation between logits of observed ($_5q_0$) and standard survival function ($l_5$) for each period preceding the inquiry. As @moultrie_etal2013, we set the slope values as $\beta = 1$. Therefore,

$$ Yobs^t_x = \alpha^t + \beta * Ystd_x$$ 
$$\alpha^t = Yobs^t_x - Ystd_x. $$

## Step 2: from standard $l_x$ and $\alpha$, compute $l_x^t$

Then, by using the estimated $\alpha$ values, we can compute a set of survival functions $l_5$, $l_{10}$ and $l_{15}$ for each period earlier than the date of inquiry:

$$ l_x^t = \frac{1}{1 + \exp[2(\alpha^t + Ystd_x)]}.$$

## Step 3: compute $_nL_x$

Using estimated values for $l^t_5$, $l^t_{10}$ and $l^t_{15}$ and $l^t_0 = 1$, we compute the person-years lived between ages $x$ and $x + 5$, for $x = 0$, $5$ and $10$:

$$ _nL^t_x = 5 * l^t_{x+5} + _na_x * (l^t_x -l^t_{x+5}), $$
where $_5a_0 = 0.50$, $_5a_5 = 2$ and $_5a_{10} = 2.5$ by default (these values can be modified in the function by the user).

## Step 4: compute survivorship ratios $_nP_x^t$

$$_5P_0^t = \frac{_5L_0^t}{5 l_0}$$

$$_5P_5^t = \frac{_5L_5^t}{_5L_0^t}$$
$$_5P_{10}^t = \frac{_5L_{10}^t}{_5L_5^t}$$

## Step 5: define $_5S_x^t$ and compute cohort $^cS_x$^[We prefer to call the @moultrie_etal2013 version $^cL_x$ as $_5^cS_x$ to highlight the five-year period and to avoid confusing it with life table $_nL_x$]

We compute $_5S_x^t$ as the survivorship ratio between ages $x$ and $x+5$ in periods $t$ equal 0-4, 5-9 and 10-14 before the inquiry.

Then,

$$ _5S_0^{0-4} = _5P_0^{0-4} $$

$$ _5S_0^{5-9} = _5P_0^{5-9} $$

$$ _5S_0^{10-14} = _5P_0^{10-14} $$

$$ _5S_5^{0-4} = _5P_5^{0-4} $$

$$ _5S_5^{5-9} = _5P_5^{5-9} $$

$$ _5S_{10}^{0-4} = _5P_{10}^{0-4}, $$
then:

$$ _5^cS_x = {_5S_0^{x}} {_5S_5^{x-5}} ... {_5S_x^{0}}, $$
and

$$ _5^cS_0 = {_5S_0^{0-4}} = {_5P_0^{0-4}}$$

$$ _5^cS_5 = {_5S_5^{0-4}} {_5S_0^{5-9}} = {_5P_5^{0-4}} {_5P_0^{5-9}}$$

$$ _5^cS_{10} = {_5S_{10}^{0-4}} {_5S_5^{5-9}} {_5S_0^{10-14}} = {_5P_{10}^{0-4}} {_5P_5^{5-9}} {_5P_0^{10-14}}.$$

## Step 6: reconstruct $B^t$

$$ B^{x - 2.5} = \frac{ _5P_{0-4} } { 5 _5^cS_0 }  $$

$$ B^{x - 7.5} = \frac{ _5P_{5-9} } { 5 _5^cS_5 }  $$

$$ B^{x - 12.5} = \frac{ _5P_{10-14} } { 5 _5^cS_{10} }  $$

# Next steps

* Update $_na_x$ to $_na_x^t$, e.g., allow the average years lived for those who died within ages $x$ and $x+n$ to vary in time by taking values from life tables of periods 0-4, 5-9 and 10-14 years earlier than the inquiry;

* Estimate a life table for the five years before the Census based on the five years life tables of WPP, without requiring the inputs of $_5q_0$ and $_{15}q_{45}$ and the calculation of $alpha$ from a standard survival function. 

# References